-- CREATE DATABASE storedb;

CREATE TABLE users (id SERIAL PRIMARY KEY, firstname VARCHAR(40) NOT NULL, lastname VARCHAR(40), password VARCHAR NOT NULL);
CREATE TABLE products (id SERIAL PRIMARY KEY, name VARCHAR(40) NOT NULL, price INTEGER NOT NULL);
CREATE TABLE orders (id SERIAL PRIMARY KEY, status CHAR(8), uid INTEGER REFERENCES users(id));
CREATE TABLE orderProducts (id SERIAL PRIMARY KEY, quantity INTEGER, oid INTEGER REFERENCES orders(id), pid INTEGER REFERENCES products(id));